apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: loki-stack
  namespace: wego-system
resources:
- app.yaml
- loki-stack-gitops-deploy.yaml
- loki-stack-gitops-source.yaml
