apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: microservices-demo
  namespace: wego-system
resources:
- app.yaml
- microservices-demo-gitops-deploy.yaml
- microservices-demo-gitops-source.yaml
