apiVersion: v1
data:
  config: |
    FluxNamespace: wego-system
    WegoNamespace: wego-system
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: weave-gitops-config
  namespace: wego-system
