apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: ingress-nginx
  namespace: wego-system
resources:
- app.yaml
- ingress-nginx-gitops-deploy.yaml
- ingress-nginx-gitops-source.yaml
