---
apiVersion: wego.weave.works/v1alpha1
kind: Application
metadata:
  labels:
    wego.weave.works/app-identifier: wego-d2f06e03641df59ff2162395d0756967
  name: podinfo-deploy
  namespace: wego-system
spec:
  branch: main
  config_url: ssh://git@github.com/sympatheticmoose/weave-gitops-multicluster-demo.git
  deployment_type: kustomize
  path: ./
  source_type: git
  url: ssh://git@github.com/sympatheticmoose/podinfo-deploy.git
